# Generated by Django 5.1.1 on 2025-11-07 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecom_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
