# Generated by Django 5.2.7 on 2025-11-08 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecom_app", "0002_remove_product_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
